apiVersion: v1
kind: Service
metadata:
  name: containerized-webapi-service
  namespace: flask-app
spec:
  selector:
    app: containerized-webapi
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 6000
      nodePort: 30080